const $=id=>document.getElementById(id);let histories=[],timer;
const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
const orderOf=h=>h?.bill?.order||h?.order||h;
const customerOf=h=>orderOf(h)?.foodCart?.customer||{};
const itemsOf=h=>orderOf(h)?.foodCart?.itemList||[];
const totalOf=h=>h?.bill?.totalCost??itemsOf(h).reduce((n,i)=>n+Number(i.cost||0)*Number(i.quantity||0),0);
function toast(t,type="success"){clearTimeout(timer);$("adminToast").textContent=t;$("adminToast").className=`toast ${type}`;timer=setTimeout(()=>$("adminToast").classList.add("hidden"),2600)}
function fmtDate(v){if(!v)return"—";const d=new Date(v);return Number.isNaN(d.getTime())?esc(v):d.toLocaleString()}
function render(){const q=$("orderSearch").value.trim().toLowerCase();$("orderRows").innerHTML="";histories.filter(h=>{const o=orderOf(h),c=customerOf(h);return [o?.orderId,o?.orderStatus,c?.firstName,c?.lastName,c?.email].join(" ").toLowerCase().includes(q)}).forEach(h=>{const o=orderOf(h),c=customerOf(h),items=itemsOf(h),tr=document.createElement("tr");tr.innerHTML=`<td><strong>#${esc(o?.orderId??"—")}</strong></td><td>${esc([c.firstName,c.lastName].filter(Boolean).join(" ")||c.email||"—")}</td><td>${fmtDate(o?.orderDate)}</td><td><span class="status-pill">${esc(o?.orderStatus||"Unknown")}</span></td><td>${items.length}</td><td>₹${Number(totalOf(h)||0).toFixed(2)}</td><td><div class="table-actions"><button class="edit-button view-order">View</button><button class="edit-button sync-order">Update</button><button class="delete-button delete-order">Delete</button></div></td>`;tr.querySelector(".view-order").onclick=()=>view(h);tr.querySelector(".sync-order").onclick=()=>update(h);tr.querySelector(".delete-order").onclick=()=>remove(h);$("orderRows").appendChild(tr)})}
async function view(h){const id=orderOf(h)?.orderId;try{const o=await API.getOrderById(id),c=o?.foodCart?.customer||{},items=o?.foodCart?.itemList||[];$("orderModalTitle").textContent=`Order #${id}`;$("orderDetail").innerHTML=`<div class="order-admin-summary"><div><span>Customer</span><strong>${esc([c.firstName,c.lastName].filter(Boolean).join(" ")||c.email||"—")}</strong></div><div><span>Status</span><strong>${esc(o.orderStatus||"Unknown")}</strong></div><div><span>Order date</span><strong>${fmtDate(o.orderDate)}</strong></div></div><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Item</th><th>Category</th><th>Price</th><th>Quantity</th></tr></thead><tbody>${items.map(i=>`<tr><td>${esc(i.itemName)}</td><td>${esc(i.category?.categoryName||"—")}</td><td>₹${Number(i.cost||0).toFixed(2)}</td><td>${esc(i.quantity)}</td></tr>`).join("")||'<tr><td colspan="4">No items returned.</td></tr>'}</tbody></table></div>`;$("orderModal").classList.remove("hidden")}catch(e){toast(e.message||"Unable to load order.","error")}}
async function update(h){const o=orderOf(h),c=customerOf(h);try{await API.updateOrder(o.orderId,c.customerId);toast("Order updated.");await load(false)}catch(e){toast(e.message||"Unable to update order.","error")}}
async function remove(h){const id=orderOf(h)?.orderId;if(!confirm(`Delete order #${id}?`))return;try{await API.removeOrder(id);histories=histories.filter(x=>orderOf(x)?.orderId!==id);render();toast("Order deleted.")}catch(e){toast(e.message||"Unable to delete order.","error")}}
async function load(show=true){if(show){$("orderLoading").classList.remove("hidden");$("orderTableWrap").classList.add("hidden")}$("orderMessage").classList.add("hidden");try{histories=await API.getAllOrderHistory();if(!Array.isArray(histories))throw new Error("Order history API did not return a list.");render();$("orderTableWrap").classList.remove("hidden")}catch(e){$("orderMessage").textContent=e.message||"Unable to load orders.";$("orderMessage").className="message error"}finally{$("orderLoading").classList.add("hidden")}}
$("orderSearch").oninput=render;$("refreshOrders").onclick=()=>load();$("closeOrderModal").onclick=()=>$("orderModal").classList.add("hidden");$("orderModal").onclick=e=>{if(e.target===$("orderModal"))$("orderModal").classList.add("hidden")};load();