const $=id=>document.getElementById(id);let items=[],categories=[],editing=null,timer;
const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
function toast(t,type="success"){clearTimeout(timer);$("adminToast").textContent=t;$("adminToast").className=`toast ${type}`;timer=setTimeout(()=>$("adminToast").classList.add("hidden"),2500)}
function render(){const q=$("itemSearch").value.trim().toLowerCase();$("itemRows").innerHTML="";items.filter(i=>(i.itemName||"").toLowerCase().includes(q)||(i.category?.categoryName||"").toLowerCase().includes(q)).forEach(i=>{const tr=document.createElement("tr");tr.innerHTML=`<td><strong>${esc(i.itemName)}</strong></td><td>${esc(i.category?.categoryName||"—")}</td><td>₹${Number(i.cost||0).toFixed(2)}</td><td>${esc(i.quantity)}</td><td><div class="table-actions"><button class="edit-button">Edit</button><button class="delete-button">Delete</button></div></td>`;tr.querySelector(".edit-button").onclick=()=>open(i);tr.querySelector(".delete-button").onclick=()=>remove(i);$("itemRows").appendChild(tr)})}
function options(){return categories.map(c=>`<option value="${c.categoryId}">${esc(c.categoryName)}</option>`).join("")}
function open(i=null){editing=i;$("itemModalTitle").textContent=i?"Edit Food Item":"Add Food Item";$("itemForm").reset();$("itemCategory").innerHTML=options();if(i){$("itemName").value=i.itemName||"";$("itemCost").value=i.cost??"";$("itemQuantity").value=i.quantity??"";$("itemCategory").value=i.category?.categoryId??""}$("itemModal").classList.remove("hidden")}
function close(){$("itemModal").classList.add("hidden");editing=null}
function payload(){const p={catergoryId:Number($("itemCategory").value),cost:Number($("itemCost").value),itemName:$("itemName").value.trim(),quantity:Number($("itemQuantity").value)};if(editing)p.itemId=editing.itemId;return p}
async function load(){try{[items,categories]=await Promise.all([API.getAllItems(),API.getAllCategories()]);if(!Array.isArray(items)||!Array.isArray(categories))throw new Error("Item or category API did not return a list.");render();$("itemTableWrap").classList.remove("hidden")}catch(e){$("itemMessage").textContent=e.message||"Unable to load food items.";$("itemMessage").className="message error"}finally{$("itemLoading").classList.add("hidden")}}
async function remove(i){if(!confirm(`Delete ${i.itemName}?`))return;try{await API.deleteItem({catergoryId:i.category?.categoryId,cost:i.cost,itemId:i.itemId,itemName:i.itemName,quantity:i.quantity});items=items.filter(x=>x.itemId!==i.itemId);render();toast("Food item deleted.")}catch(e){toast(e.message||"Unable to delete food item.","error")}}
$("addItemButton").onclick=()=>open();$("closeItemModal").onclick=close;$("itemModal").onclick=e=>{if(e.target===$("itemModal"))close()};$("itemSearch").oninput=render;
$("itemForm").onsubmit=async e=>{e.preventDefault();const b=$("saveItemButton");try{b.disabled=true;b.textContent="Saving...";const result=editing?await API.updateItem(payload()):await API.addItem(payload());if(editing)items=items.map(i=>i.itemId===editing.itemId?result:i);else items.push(result);close();render();toast("Food item saved.")}catch(err){toast(err.message||"Unable to save food item.","error")}finally{b.disabled=false;b.textContent="Save Food Item"}};
load();